#include <iostream>
#include <string>
#include <stack>
#include <linked_lists/sll/sll.hpp>
#include <linked_lists/sll/utils.hpp>

using namespace linked_lists;

void TestForwardListString() {
    using namespace std::literals;
    forward_list<std::string> list;
    std::cout << "==============================\n";
    std::cout << "> Back: " << (list.empty() ? "" : *list.begin()) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> push_front: cow, elephant, lion" << std::endl;
    list.push_front("cow"s);
    list.push_front("elephant"s);
    list.push_front("lion"s);
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : *list.begin()) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> pop_front" << std::endl;
    list.pop_front();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : *list.begin()) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> pop_front" << std::endl;
    list.pop_front();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : *list.begin()) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> pop_front" << std::endl;
    list.pop_front();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : *list.begin()) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> pop_front (list is empty)" << std::endl;
    list.pop_front();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : *list.begin()) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> push_front: dolphin, shark, cow, elephant, lion" << std::endl;
    list.push_front("dolphin"s);
    list.push_front("shark"s);
    list.push_front("cow"s);
    list.push_front("elephant"s);
    list.push_front("lion"s);
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : *list.begin()) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> push_front: cow, elephant, lion" << std::endl;
    list.push_front("cow"s);
    list.push_front("elephant"s);
    list.push_front("lion"s);
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : *list.begin()) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> Clear" << std::endl;
    list.clear();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : *list.begin()) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
}

void TestForwardListInt() {
    forward_list<int> list;
    std::cout << "==============================\n";
    std::cout << "> Back: " << (list.empty() ? "" : std::to_string(*list.begin())) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> push_front: 7, 9, 12" << std::endl;
    list.push_front(7);
    list.push_front(9);
    list.push_front(12);
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : std::to_string(*list.begin())) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> pop_front" << std::endl;
    list.pop_front();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : std::to_string(*list.begin())) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> pop_front" << std::endl;
    list.pop_front();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : std::to_string(*list.begin())) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> pop_front" << std::endl;
    list.pop_front();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : std::to_string(*list.begin())) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> pop_front (list is empty)" << std::endl;
    list.pop_front();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : std::to_string(*list.begin())) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> push_front: 7, 9, 12" << std::endl;
    list.push_front(7);
    list.push_front(9);
    list.push_front(12);
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : std::to_string(*list.begin())) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
    std::cout << "> Clear" << std::endl;
    list.clear();
    std::cout << "> Print: " << list;
    std::cout << std::endl;
    std::cout << "> Back: " << (list.empty() ? "" : std::to_string(*list.begin())) << std::endl;
    std::cout << "> Size: " << list.size() << std::endl;
    std::cout << "> Empty: " << (list.empty() ? "Yes" : "No") << std::endl;
    std::cout << "==============================\n";
}

void TestCopyMove() {
    using namespace std::literals;


    std::cout << "==============================\n";
    std::cout << "> Initialization\n";
    std::cout << "==============================\n";
    std::cout << "> forward_list<std::string> list1 = forward_list<std::string>({ \"hello\"s,\"world\"s }); // std::initializer_list&& <- move" << std::endl;
    forward_list<std::string> list1 = forward_list<std::string>({ "hello"s,"world"s });
    std::cout << "> forward_list<std::string> list2 = {\"blue\"s,\"red\"s}; // std::initializer_list&& <- move" << std::endl;
    forward_list<std::string> list2 = { "blue"s,"red"s };
    std::cout << "> forward_list<std::string> list3({ \"cat\", \"dog\" }); // std::initializer_list&& <- move" << std::endl;
    forward_list<std::string> list3({ "cat", "dog" });
    std::cout << "> forward_list<std::string> list4; // <- default empty constructor" << std::endl;
    forward_list<std::string> list4;
    std::cout << "> list4.push_front(\"one\");" << std::endl;
    std::cout << "> list4.push_front(\"two\");" << std::endl;
    std::cout << "> list4.push_front(\"five\");" << std::endl;
    list4.push_front("one");
    list4.push_front("two");
    list4.push_front("five");
    std::cout << "==============================\n";
    std::cout << "> Print list1: " << list1 << std::endl;
    std::cout << "> Print list2: " << list2 << std::endl;
    std::cout << "> Print list3: " << list3 << std::endl;
    std::cout << "> Print list4: " << list4 << std::endl;
    std::cout << "==============================\n";
    std::cout << "> Copy\n";
    std::cout << "==============================\n";
    std::cout << "> Print list1: " << list1 << std::endl;
    std::cout << "> {" << std::endl;
    std::cout << "> \tforward_list<std::string> list_r1 = list1;" << std::endl;
    {
        forward_list<std::string> list_r1 = list1;
        std::cout << "> \tPrint list_r1: " << list_r1 << std::endl;
        std::cout << "> \tPrint list1: " << list1 << std::endl;
    }
    std::cout << "> }" << std::endl;
    std::cout << "> Print list1: " << list1 << std::endl;
    std::cout << "> list_r1 deleted" << std::endl;
    std::cout << "==============================\n";
    std::cout << "> Print list2: " << list2 << std::endl;
    std::cout << "> forward_list<std::string> list_r2(list2);" << std::endl;
    forward_list<std::string> list_r2(list2);
    std::cout << "> Print list_r2: "<< list_r2 << std::endl;
    std::cout << "> Print list2: "<< list2 << std::endl;
    std::cout << "> list_r2.clear();" << std::endl;
    list_r2.clear();
    std::cout << "> Print list_r2: "<< list_r2 << std::endl;
    std::cout << "> Print list2: "<< list2 << std::endl;
    std::cout << "==============================\n";
    std::cout << "> Move\n";
    std::cout << "==============================\n";
    std::cout << "> Print list3: "<< list3 << std::endl;
    std::cout << "> forward_list<std::string> list_r3;" << std::endl;
    forward_list<std::string> list_r3;
    std::cout << "> list_r3 = std::move(list3);" << std::endl;
    list_r3 = std::move(list3);
    std::cout << "> Print list3: "<< list3 << std::endl;
    std::cout << "> Print list_r3: "<< list_r3 << std::endl;
    std::cout << "==============================\n";
    std::cout << "> Print list4: "<< list4 << std::endl;
    std::cout << "> forward_list<std::string> list_r4(std::move(list4));" << std::endl;
    forward_list<std::string> list_r4(std::move(list4));
    std::cout << "> Print list4: "<< list4 << std::endl;
    std::cout << "> Print list_r4: "<< list_r4 << std::endl;
    std::cout << "==============================\n";
}

int main() {
    std::cout << "//////////////////////////////\n";
    std::cout << "// Scalar test              //\n";
    std::cout << "//////////////////////////////\n\n";
    TestForwardListInt();
    std::cout << "\n//////////////////////////////\n";
    std::cout << "// Class (std::string) test //\n";
    std::cout << "//////////////////////////////\n\n";
    TestForwardListString();
    std::cout << "\n//////////////////////////////\n";
    std::cout << "// Copy & Move test         //\n";
    std::cout << "//////////////////////////////\n\n";
    TestCopyMove();
    return 0;
}